name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Publish .NET Project
        run: |
          dotnet publish BlazorApp1/BlazorApp1.csproj -c Release -o release --nologo

      # Cambia la base-tag en index.html desde '/' a '/BlazorApp1/' para que funcione con GitHub Pages
      - name: Change base-tag in index.html
        run: |
          find release/wwwroot -name "*.html" -exec sed -i 's/<base href="\/" \/>/<base href="\/BlazorApp1\/" \/>/g' {} \;

      # Añade archivo .nojekyll para evitar procesamiento con Jekyll
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll

      # Elimina la rama gh-pages si existe y crea una nueva
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: release/wwwroot
          branch: gh-pages
          clean: true         # Elimina archivos existentes en la rama
          clean-exclude: |    # Archivos que queremos mantener (opcional)
            .gitignore
            README.md
          force: true         # Fuerza la actualización incluso si hay conflictos
          token: ${{ secrets.DEPLOY_BLAZOR }}
          commit-message: "Deploy Blazor Web App to GitHub Pages"
          git-config-name: "GitHub Actions"
          git-config-email: "actions@github.com"
          single-commit: true # Mantiene solo el último commit en la rama gh-pages
